import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Real Estate | Purple.dev",
    description: "Generated by Walter Daniel Carrizo",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="h-screen flex items-center justify-center bg-primary">
            {children}
        </div>
    );
}
