import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import { Inter } from 'next/font/google';
import { auth } from '@/auth';
import { Toaster } from '@/components/ui/toaster';

import './globals.css';

const inter = Inter({subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Real Estate | Purple.dev",
  description: "Generated by Walter Daniel Carrizo",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
        <body className={inter.className}>
          <SessionProvider session={session}>
              {children}
          </SessionProvider>
          <Toaster />
        </body>
      </html>
  );
}
